const STATUS_NEWS = {
    DRAFT: 'NHAP',
    PUBLISHED: 'XUAT_BAN',
}

const STATUS_NEWS_LABELS = {
    NHAP: 'Bản nháp',
    XUAT_BAN: 'Đã xuất bản',
}

const STATUS_NEWS_OPTIONS = [
    { value: STATUS_NEWS.DRAFT, label: STATUS_NEWS_LABELS[STATUS_NEWS.DRAFT] },
    { value: STATUS_NEWS.PUBLISHED, label: STATUS_NEWS_LABELS[STATUS_NEWS.PUBLISHED] },
]

export { STATUS_NEWS, STATUS_NEWS_LABELS, STATUS_NEWS_OPTIONS };