server {
  listen 8881;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Cache static assets aggressively
  location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|woff2?|ttf|map)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # SPA fallback to index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
